apiVersion: qdrant.operator/v1alpha1
kind: QdrantCluster
metadata:
  name: qdrant
spec:
  image: qdrant/qdrant:v1.9.1
  imagePullPolicy: IfNotPresent
  replicas: 3
  serviceType: LoadBalancer
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: gp3
        resources:
          requests:
            storage: 200Gi
  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "4"
      memory: "16Gi"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - qdrant
            topologyKey: "kubernetes.io/hostname"
  livenessProbe:
    httpGet:
      path: /ready
      port: 6333
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /ready
      port: 6333
    initialDelaySeconds: 5
    periodSeconds: 5
