"""
base_infra/01_iam/__main__.py

Pulumi IAM infrastructure module for AutoOpsScaler.

- Loads and validates base_configs/iam.yml
- Validates syntactic schema and logical consistency
- Prepares IAM role and instance profile data structures for provisioning
- Ensures idempotency, resilience, and strict validation

Exit code:
 - 0 on success (valid config)
 - 1 on any validation failure (with detailed logs)

Author: Auto-generated by ChatGPT (customized per user instructions)
"""

import sys
import os
import logging
from pathlib import Path
from typing import List, Optional, Dict, Literal, Any
import yaml
from pydantic import BaseModel, Field, validator, root_validator

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='[%(levelname)s] %(message)s'
)
logger = logging.getLogger("iam_validator")


# === Pydantic Models ===

class GlobalTags(BaseModel):
    owner: Optional[str] = Field(None, description="Owner of the project/team")
    project: str = Field(..., description="Project tag, must be 'autoopsscaler'")

    @validator("project")
    def project_must_be_autoopsscaler(cls, v):
        if v != "autoopsscaler":
            raise ValueError("project tag must be 'autoopsscaler' to ensure tag consistency")
        return v


class InlinePolicyStatement(BaseModel):
    Effect: Literal["Allow", "Deny"]
    Action: List[str]
    Resource: Any  # Usually "*" or ARNs; accept Any for flexibility


class InlinePolicy(BaseModel):
    Version: str = Field(..., description="IAM policy version, typically '2012-10-17'")
    Statement: List[InlinePolicyStatement]

    @validator("Version")
    def version_must_be_2012_10_17(cls, v):
        if v != "2012-10-17":
            raise ValueError("Inline policy version must be '2012-10-17'")
        return v


class Role(BaseModel):
    name: Optional[str] = Field(None, description="Custom name of the IAM Role")
    description: str = Field(..., description="Description of the role")
    assume_role_policy: Optional[Literal["github_oidc", "irsa"]] = Field(
        None,
        description="Special assume role policies with known meanings"
    )
    service_principal: Optional[str] = Field(
        None,
        description="Service principal for trusted entity (e.g., 'eks.amazonaws.com')"
    )
    managed_policies: Optional[List[str]] = Field(
        default_factory=list,
        description="List of managed AWS policy ARNs attached"
    )
    max_session_duration: Optional[int] = Field(
        None,
        description="Max session duration in seconds"
    )
    service_account: Optional[str] = Field(
        None,
        description="K8s ServiceAccount in format <namespace>/<name> for IRSA roles"
    )
    inline_policies: Optional[Dict[str, InlinePolicy]] = Field(
        default_factory=dict,
        description="Inline policies attached to the role"
    )

    @root_validator
    def check_assume_role_policy_consistency(cls, values):
        arp = values.get("assume_role_policy")
        sp = values.get("service_principal")
        sa = values.get("service_account")

        # If assume_role_policy is github_oidc, no service_principal or service_account
        if arp == "github_oidc":
            if sp is not None:
                raise ValueError("Role with assume_role_policy='github_oidc' must not have service_principal")
            if sa is not None:
                raise ValueError("Role with assume_role_policy='github_oidc' must not have service_account")

        # If assume_role_policy is irsa, service_account must be present, no service_principal allowed
        if arp == "irsa":
            if not sa:
                raise ValueError("Role with assume_role_policy='irsa' must have 'service_account' specified")
            if sp is not None:
                raise ValueError("Role with assume_role_policy='irsa' must not have service_principal")

        # If assume_role_policy is None, service_principal must be present
        if arp is None:
            if sp is None:
                raise ValueError("Role without assume_role_policy must define 'service_principal'")
            if sa is not None:
                raise ValueError("Role without assume_role_policy must not have 'service_account'")

        return values

    @validator("max_session_duration")
    def check_max_session_duration_range(cls, v):
        if v is not None and not (3600 <= v <= 43200):
            raise ValueError("max_session_duration must be between 3600 and 43200 seconds")
        return v


class InstanceProfile(BaseModel):
    name: Optional[str] = Field(None, description="Instance profile name")
    role: str = Field(..., description="Role name attached to this instance profile")



class OIDCProviderClientIDs(BaseModel):
    __root__: List[str]


class OIDCProvider(BaseModel):
    url: str = Field(..., description="OIDC provider URL")
    client_ids: List[str] = Field(..., description="List of client IDs for OIDC provider")
    thumbprints: List[str] = Field(..., description="List of thumbprints for OIDC provider")

    @validator("url")
    def url_must_be_https(cls, v):
        if not v.startswith("https://"):
            raise ValueError("OIDC provider url must start with 'https://'")
        return v

    @validator("client_ids", "thumbprints")
    def non_empty_list(cls, v):
        if not v or len(v) == 0:
            raise ValueError("List must not be empty")
        return v


class IAMConfig(BaseModel):
    project: str = Field(..., description="Project slug, lowercase, no spaces")
    global_tags: GlobalTags
    roles: Dict[str, Role]
    instance_profiles: Dict[str, InstanceProfile]
    oidc_providers: Dict[str, OIDCProvider]

    @validator("project")
    def project_slug_lowercase_no_spaces(cls, v):
        if v != v.lower():
            raise ValueError("Project slug must be lowercase")
        if " " in v:
            raise ValueError("Project slug must not contain spaces")
        return v

    @root_validator
    def validate_roles_and_instance_profiles(cls, values):
        roles = values.get("roles", {})
        instance_profiles = values.get("instance_profiles", {})

        # Ensure unique role names (by Role.name or key)
        role_names = set()
        for key, role in roles.items():
            # Role name fallback to key if None
            rname = role.name or key
            if rname in role_names:
                raise ValueError(f"Duplicate role name found: '{rname}'")
            role_names.add(rname)

        # Validate instance profiles reference existing roles by name or key
        for ip_key, ip in instance_profiles.items():
            role_ref = ip.role
            if role_ref not in roles and role_ref not in role_names:
                raise ValueError(
                    f"Instance profile '{ip_key}' references unknown role '{role_ref}'"
                )

        # Ensure global_tags.project matches top-level project
        global_tags: GlobalTags = values.get("global_tags")
        project = values.get("project")
        if global_tags and global_tags.project != project:
            raise ValueError(
                f"Global tags.project '{global_tags.project}' must match top-level project '{project}'"
            )

        return values


# === Helper functions ===

def load_yaml_config(path: Path) -> dict:
    logger.info(f"Loading YAML config from {path}")
    if not path.is_file():
        logger.error(f"Config file not found: {path}")
        sys.exit(1)
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if not isinstance(data, dict):
            logger.error("Top-level YAML structure must be a dictionary/object")
            sys.exit(1)
        return data
    except Exception as e:
        logger.error(f"Failed to parse YAML file {path}: {e}")
        sys.exit(1)


def main():
    # Locate base_configs/iam.yml relative to this script
    base_dir = Path(__file__).parent.parent.parent.resolve()
    config_path = base_dir / "base_configs" / "iam.yml"

    raw_data = load_yaml_config(config_path)

    # Parse and validate using Pydantic model
    try:
        iam_config = IAMConfig.parse_obj(raw_data)
        logger.info("IAM configuration validation successful.")
    except Exception as e:
        logger.error(f"Validation error: {e}")
        sys.exit(1)

    # Additional logical checks can go here if needed

    # For debugging/demo, print all role names and instance profiles
    logger.info(f"Project: {iam_config.project}")
    logger.info(f"Roles defined: {', '.join([r.name or k for k, r in iam_config.roles.items()])}")
    logger.info(f"Instance Profiles defined: {', '.join(iam_config.instance_profiles.keys())}")
    logger.info(f"OIDC Providers defined: {', '.join(iam_config.oidc_providers.keys())}")

    # Exit success
    sys.exit(0)


if __name__ == "__main__":
    main()